services:
  _image:
    image: music-downloader
    command: ["echo", "build completed"]
    build:
      context: .
      dockerfile: Dockerfile

  redis:
    image: "redis:alpine"

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./config.yaml
        target: /app/config.yaml
    depends_on:
      - redis
      - _image
    environment:
      - PYTHONUNBUFFERED=1
    command: python bot.py
    restart: on-failure

  worker:
    extends:
      service: bot
    volumes:
      - type: bind
        source: ./config.yaml
        target: /app/config.yaml
      - type: volume
        source: ./music
        target: /app/music
    depends_on:
      - redis
      - _image
    environment:
      - PYTHONUNBUFFERED=1
    command: taskiq worker worker_app:broker worker.tasks --log-level INFO --workers=2
    restart: always