version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./config.yaml
        target: /app/config.yaml
    environment:
      - PYTHONUNBUFFERED=1
    command: python bot.py
    restart: on-failure

  worker:
    extends:
      service: bot
    volumes:
      - type: bind
        source: ./config.yaml
        target: /app/config.yaml
    environment:
      - PYTHONUNBUFFERED=1
    command: taskiq worker worker_app:broker worker.tasks --log-level INFO --workers=2
    restart: on-failure