"""Initial

Revision ID: 24c7ef85d795
Revises: 
Create Date: 2024-04-11 07:44:47.858478

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24c7ef85d795"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("sudo", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("firstname", sa.String(), nullable=False),
        sa.Column("lastname", sa.String(), nullable=True),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("banned", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_on", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("admins")
    # ### end Alembic commands ###
